title: My blog  
author: JuanPSaladent 
email:juanpsaladent@gmail.com
description: > TODO BIEN TODO BONITO


# social links
twitter_username:jSaladent
github_username: JuanPSaladent
Date:2021-02-19
show_excerpts: true
permalink           : date
paginate_path       : /page:num
timezone            : null

quiet               : false
verbose             : false
defaults            : []

liquid:
  error_mode        : warn
  strict_filters    : false
  strict_variables  : false
