
author: Juan Pablo Saladent
email: juanpsaladent@gmail.com
description: > #DESDE QUE TE DUSNUDASTE PA MI MENTE TE MUDASTE.

theme:minima
# social links
twitter_username: JSaladent
github_username: JuanPSaladent

show_excerpts: true  
